task:
  title: What is the sentiment?
dataset:
  directory: dataset/small_imdb_reviews/
  data_type: text
  judgements_file: outputs/small_imdb_reviews/labels.csv
label:
  type: classification
  classes:
    - Negative
    - Positive
model:
  directory: outputs/small_imdb_reviews/models/
  pretrain_file: dataset/imdb_pretrain.csv
user: chris
