task:
  title: Label this sequence with its NERs
dataset:
  directory: dataset/sequence_labelling/
  data_type: json
  judgements_file: outputs/sequence_labelling/labels.csv
label:
  type: sequence
  default_class: O
  classes:
    - LOC
    - ATTR
    - HOME-TYPE
    - ACT
    - AMENITIES
model:
  directory: outputs/sequence_labelling/models/
  pretrain_file: dataset/pretrain.csv
user: chris
